#!/bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

ifclass EC2 || fcopy -M /etc/cloud/ds-identify.cfg
fcopy -M /etc/cloud/cloud.cfg.d/20_use_netplan.cfg

rm -f $target/etc/ssh/ssh_host* 2>/dev/null

for F in /etc/machine-id /var/lib/dbus/machine-id; do
    if [ -f $F ]; then
        : > $F
    else
        touch $F
    fi
done

if [ ! -d /etc/systemd/networkd.conf.d ]; then
    mkdir -p /etc/systemd/networkd.conf.d
fi

cat <<EOF > /etc/systemd/networkd.conf.d/10-carthage-duid-link-layer.conf
[DHCPv4]
DUIDType=link-layer

[DHCPv6]
DUIDType=link-layer
EOF

exit $error
