plugins:
- https://github.com/hadron/carthage-base
- https://github.com/hadron/carthage-aws
authorized_keys: /dev/null
aws:
  access_key_id: ${AWS_ACCESS_KEY}
  secret_access_key: ${AWS_SECRET_KEY}
  profile: ${CARTHAGE_TEST_AWS_PROFILE}
  region: us-east-1
  vpc_name: test_vpc
  vpc_dns_hostnames_enabled: true
base_dir: /tmp/carthage-base
checkout_dir: /tmp/carthage-base/checkout
