# Generated by Carthage--do not edit
# Changes will be lost

[NetDev]
Name=${link.interface}
Kind=${link.local_type}
%if link.mtu:
MTUBytes=${link.mtu}
%endif
%if link.mac:
MACAddress=${link.mac}
%endif
<%block name="local_type">
# local_type block needs to be overridden
</%block>
<%block name="trailer" />
