# Generated by Carthage--do not edit
# Changes will be lost

[Match]
<%
driver = "ether"
if link.local_type == 'bridge':
    driver = 'bridge'
elif link.local_type == 'bond':
    driver = 'bond'
    %>\
%if link.mac:
Type=${driver}
MACAddress=${link.mac}
%else:
Name=${link.interface}
%endif
[Network]
<%block name="network">
# Network block needs to be overridden
</%block>
