# Generated by Carthage--do not edit
# Changes will be lost

[Match]
<%
driver = "ether"
if link.local_type == 'bridge':
    driver = 'bridge'
elif link.local_type == 'bond':
    driver = 'bond'
    %>\
%if link.mac:
Type=${driver}
MACAddress=${link.mac}
%else:
Name=${link.interface}
%endif
[Link]
<%block name="link_block">
%if link.mtu:
MTUBytes=${link.mtu}
%endif
%if link.required is False:
RequiredForOnline=no
%endif
</%block>
[Network]
%if driver == 'ether':
LLDP=yes
%if link.lldp:
EmitLLDP=yes
%endif
%endif
<%block name="network">
# Network block needs to be overridden
</%block>
<%block name="trailer" />
