# Generated by Carthage
# Do not change; changes will be lost.
[NetDev]
Name=${link.interface}
Kind=vlan
%if link.mac:
MACAddress=${link.mac}
%endif
%if link.mtu:
MTUBytes=${link.mtu}
% endif
[VLAN]
ID=${link.vlan_id}
