FROM debian:bookworm
ADD carthage*whl /dist/
ADD carthage.tar.gz /carthage
run apt update
RUN apt -y install python3 python3-pip python3-pytest virtualenv
RUN pip  install --break-system-packages /dist/carthage*whl
RUN carthage --plugin carthage.podman install_dependencies
ADD authorized.yml /authorized.yml
