FROM scratch
ADD container.tar /
ENV PYTHONPATH /carthage
ENV PATH /usr/bin:/usr/sbin:/carthage/bin
CMD ["/bin/systemd"]
VOLUME ["/layout"]
LABEL org.opencontainers.image.source https://github.com/hadron/carthage

