name: Build Carthage OCI Images
on:
  push:
    branches:
      - master
    paths:
      - carthage/**
      - oci_images/**
      - .github/workflows/images.yml

permissions:
  contents: read
  packages: write
jobs:
  build_image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt -q update
          sudo apt -y install systemd-container socat qemu-utils fai-setup-storage fai-server python3-mako python3-sh python3-pyvmomi python3-yaml python3-pytest python3-lmdb python3-dateutil ansible python3-six genisoimage
      - name: Login to ghcr.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{github.actor}}
          password: ${{github.token}}
          registry: ghcr.io
          

      - name: Build image
        run: |
          sudo PYTHONPATH=$(pwd) python3 ./bin/carthage-runner ./oci_images build
          sudo -E podman push carthage ghcr.io/hadron/carthage:latest

      - name: upload ansible log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: images ansible.log
          path: oci_images/ansible.log


