name: Build Carthage OCI Images
on:
  push:
    branches:
      - master
    paths:
      - carthage/*
      - oci_images/*
      - .github/workflows/images.yml

permissions:
  contents: read
  packages: write
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt -q update
          sudo apt -y install systemd-container socat qemu-utils fai-setup-storage fai-server python3-mako python3-sh python3-pyvmomi python3-yaml python3-pytest ansible genisoimage

      - name: Build image
        run: |
          sudo PYTHONPATH=$(pwd) python3 oci_images/build_container_image.py
          sudo -E podman login --username ${{github.actor}} --password ${{github.token}} ghcr.io
          sudo -E podman push carthage ghcr.io/hadron/carthage:latest

      - name: upload ansible log
        uses: actions/upload-artifact@v3
        with:
          name: images ansible.log
          path: oci_images/ansible.log


