name: Build and Test

on:
  push:
  release:
    types: [create]
    
jobs:
  build_python_dist:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build toml

    - name: Build 
      run: |
        make dist

    - name: upload_artifact
      uses: actions/upload-artifact@v3
      with:
        name: Python Distributions
        path: dist/*

    - name: Check Version consistency
      if: github.ref_type == 'tag'
      shell: python
      run: |
        import toml
        with open('pyproject.toml', 'rt') as f:
          result = toml.load(f)
        assert 'v'+result['project']['version'] == '${{github.ref_name}}'
        