name: Test Carthage
on:
- push
- pull_request
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          sudo apt -q update
          sudo apt -y install systemd-container socat qemu-utils fai-setup-storage fai-server python3-mako python3-sh python3-pyvmomi python3-yaml python3-pytest python3-dateutil ansible genisoimage

      - name: run tests
        run: |
          sudo TZ=US/Eastern PYTHONPATH=$(pwd) pytest-3 -v --carthage-config=.github/test_config.yml --log-cli-level=debug
          